### ISSUE TITLE
Update this example to rc.1

### ISSUE THREAD

**Issue by theblang** [ThorstenHans/electron-ts-ng2#3]
Running into the same exact issues you mention in your blog post [here](https://www.xplatform.rocks/2016/01/07/building-an-electron-app-using-angular2-beta0-in-typescript/). Unfortunately, using the `HashLocationStrategy` still causes Angular 2 to complain about the `base href` not being set.

**Comment by tcarlsen** [comment]
you need to get it from `@angular/common` now

```
import { provide, enableProdMode } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';
import { ROUTER_PROVIDERS } from '@angular/router';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';

import { AppComponent } from './app.component';

// enableProdMode();
bootstrap(AppComponent, [
  ROUTER_PROVIDERS,
  provide(LocationStrategy, {useClass: HashLocationStrategy})
]);
```

**Comment by theblang** [comment]
@tcarlsen Yeah, I did figure that out. Unfortunately, Angular still complains about `base href` not being set.

My `main.ts`:

```
import { bootstrap } from '@angular/platform-browser-dynamic';
import { provide } from '@angular/core';
import { ROUTER_PROVIDERS } from '@angular/router';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';
import { AppComponent } from './app.component';

bootstrap(AppComponent, [
    ROUTER_PROVIDERS,
    provide(LocationStrategy, {useClass: HashLocationStrategy})
])
```

The `stacktrace`:

```
EXCEPTION: Error in :0:0
EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
ORIGINAL STACKTRACE:
Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new BaseException (exceptions.ts:14)
    at new PathLocationStrategy (path_location_strategy.ts:23)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.template.js:34)
    at DebugAppView.AppView.create (view.ts:110)
    at DebugAppView.create (view.ts:315)
    at ComponentFactory.create (component_factory.ts:96)
    at eval (application_ref.ts:359)
    at eval (application_ref.ts:337)
    at ZoneDelegate.invoke (zone.js:323)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.ts:67)
ERROR CONTEXT:
DebugContext {_view: _View_AppComponent_Host0, _nodeIndex: 0, _tplRow: 0, _tplCol: 0}
EXCEPTION: Error in :0:0
EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
ORIGINAL STACKTRACE:
Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new BaseException (exceptions.ts:14)
    at new PathLocationStrategy (path_location_strategy.ts:23)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.template.js:34)
    at DebugAppView.AppView.create (view.ts:110)
    at DebugAppView.create (view.ts:315)
    at ComponentFactory.create (component_factory.ts:96)
    at eval (application_ref.ts:359)
    at eval (application_ref.ts:337)
    at ZoneDelegate.invoke (zone.js:323)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.ts:67)
ERROR CONTEXT:
DebugContext {_view: _View_AppComponent_Host0, _nodeIndex: 0, _tplRow: 0, _tplCol: 0}
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
ORIGINAL STACKTRACE:
Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new BaseException (http://localhost:3000/node_modules/@angular/common/src/facade/exceptions.js:17:23)
    at new PathLocationStrategy (http://localhost:3000/node_modules/@angular/common/src/location/path_location_strategy.js:22:19)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.template.js:34:32)
    at DebugAppView.AppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:66:21)
    at DebugAppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:259:44)
    at ComponentFactory.create (http://localhost:3000/node_modules/@angular/core/src/linker/component_factory.js:143:36)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:314:44)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:292:26)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
ERROR CONTEXT:
[object Object]
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
ORIGINAL STACKTRACE:
Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new BaseException (http://localhost:3000/node_modules/@angular/common/src/facade/exceptions.js:17:23)
    at new PathLocationStrategy (http://localhost:3000/node_modules/@angular/common/src/location/path_location_strategy.js:22:19)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.template.js:34:32)
    at DebugAppView.AppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:66:21)
    at DebugAppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:259:44)
    at ComponentFactory.create (http://localhost:3000/node_modules/@angular/core/src/linker/component_factory.js:143:36)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:314:44)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:292:26)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
ERROR CONTEXT:
[object Object]
STACKTRACE:
Error: Uncaught (in promise): EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
ORIGINAL STACKTRACE:
Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new BaseException (http://localhost:3000/node_modules/@angular/common/src/facade/exceptions.js:17:23)
    at new PathLocationStrategy (http://localhost:3000/node_modules/@angular/common/src/location/path_location_strategy.js:22:19)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.template.js:34:32)
    at DebugAppView.AppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:66:21)
    at DebugAppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:259:44)
    at ComponentFactory.create (http://localhost:3000/node_modules/@angular/core/src/linker/component_factory.js:143:36)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:314:44)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:292:26)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
ERROR CONTEXT:
[object Object]
    at resolvePromise (http://localhost:3000/node_modules/zone.js/dist/zone.js:538:32)
    at PromiseCompleter.reject (http://localhost:3000/node_modules/zone.js/dist/zone.js:515:14)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:295:35)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:322:35)
    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:216:44)
    at http://localhost:3000/node_modules/zone.js/dist/zone.js:571:58
    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:356:38)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost:3000/node_modules/@angular/core/src/zone/ng_zone_impl.js:36:41)
Unhandled Promise rejection: EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
ORIGINAL STACKTRACE:
Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.
    at new BaseException (http://localhost:3000/node_modules/@angular/common/src/facade/exceptions.js:17:23)
    at new PathLocationStrategy (http://localhost:3000/node_modules/@angular/common/src/location/path_location_strategy.js:22:19)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.template.js:34:32)
    at DebugAppView.AppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:66:21)
    at DebugAppView.create (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:259:44)
    at ComponentFactory.create (http://localhost:3000/node_modules/@angular/core/src/linker/component_factory.js:143:36)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:314:44)
    at eval (http://localhost:3000/node_modules/@angular/core/src/application_ref.js:292:26)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/@angular/core/src/zone/ng_zone_impl.js:45:41)
ERROR CONTEXT:
[object Object] ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedException {_wrapperMessage: "Error in :0:0", _originalException: BaseException, _originalStack: "Error: No base href set. Please provide a value fo…les/@angular/core/src/zone/ng_zone_impl.js:45:41)", _context: DebugContext, _wrapperStack: "Error: Error in :0:0↵    at ViewWrappedException.W…st:3000/node_modules/zone.js/dist/zone.js:322:35)"}
Error: Uncaught (in promise): EXCEPTION: Error in :0:0(…)
```

**Comment by tcarlsen** [comment]
Thats weird. My app is not yelling for `APP_BASE_HREF` after using `HashLocationStrategy`

**Comment by theblang** [comment]
@tcarlsen Even when using the `2.0.0-rc.1` release?

**Comment by tcarlsen** [comment]
yeah, that why its weird

**Comment by ThorstenHans** [comment]
I will look into that later this week guys

**Comment by ThorstenHans** [comment]
migrated to rc1

**Comment by ThorstenHans** [comment]
@mattblang you are relying on old an outdated version of `shim` that's why you've the issue

**Comment by theblang** [comment]
@ThorstenHans Well, I checked the version of `es6-shim` and it is at `0.35.1`, which seems to be the latest. Also, should the `HashLocationStrategy` be putting a hash mark in the URL?

**Comment by ThorstenHans** [comment]
Not for the root url
